<a href="https://colab.research.google.com/github/nicolasvargaszz/Introduction-to-data-Science/blob/main/proyecto2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Pandas Avanzado**

In [1]:
import numpy as pd
import pandas as pd
import os

In [2]:
os.listdir()

['.config',
 'Julio_2024-301-378.xlsx',
 'Julio_2024-151-300.xlsx',
 'Julio_2024-1-150.xlsx',
 'sample_data']

In [13]:
archivos = []

for documento in os.listdir():
  if documento.endswith('.xlsx'):
    if documento == 'Julio_2024-1-150.xlsx':
      archivos.append(pd.read_excel(documento, skiprows=1))
    else:
      archivos.append(pd.read_excel(documento,header=None))

In [14]:
len(archivos)

3

In [9]:
archivos[2].head()

,Ch o n i ta\nPlanilla de Salarios del Mes de Julio 2.024,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Cedula,Nombre,NaN,Relacion Laboral,Monto,Concepto,Dependencia,NaN,Cargo,NaN,Año de Ingreso
1,"122374 ROJAS DORIA, JULIO RAFAEL",NaN,CONTRATADO,NaN,2680373 SUELDO BASICO,NaN,DIRECCION GENERAL DE CULTURA Y TURISMO,NaN,NaN,2011.0,NaN
2,"141772 RUIZ DE SEGOVIA, GILDA",NaN,CONTRATADO,NaN,2680373 SUELDO BASICO,NaN,DIR. DEL INSTITUTO MUNICIPAL DE ARTE (IMA),NaN,NaN,2017.0,NaN
3,"196023 CABRERA, MARIA ALEJANDRA",NaN,NOMBRADO,NaN,804110 BONIFICACION POR GRADO ACADEMICO INTERM...,NaN,DIR. DEL INSTITUTO MUNICIPAL DE ARTE (IMA),NaN,NaN,2004.0,NaN
4,"196023 CABRERA, MARIA ALEJANDRA",NaN,NOMBRADO,NaN,254635 SUBSIDIO PARA LA SALUD,NaN,DIR. DEL INSTITUTO MUNICIPAL DE ARTE (IMA),NaN,NaN,2004.0,NaN